### ISSUE TITLE
魔改造Jeff

### ISSUE THREAD

**Issue by purin213** [recursion-teamdev-green/project#16]
![BoscRArCAAAepo-](https://user-images.githubusercontent.com/51078652/185964168-41ded5e3-6c28-4364-a5d9-0a4e8f12faf8.jpg)
案１です、レビューお願いします

_Originally posted by @purin213 in https://github.com/recursion-teamdev-green/project/discussions/15_

**Comment by purin213** [comment]
こういう感じ欲しい、とかあったら是非意見お聞きしたいです！

**Comment by jKai-Hw** [comment]
めちゃいいですね(笑)笑っちゃいました。
僕が最初に想像してたのは、グラサン描いて、髪の毛を金髪のツンツン描いてみたいなのを勝手に想像してました。
何種類か入れてもいいかもですね(笑)

**Comment by purin213** [comment]
Dqnみたいな感じっすかね笑
チャリで来たみたいな。
何パターンか作ってみますね

**Comment by jKai-Hw** [comment]
お願いします(笑)
情報集めてるときに、「プルリクOKするときなどによく使ってる」と言って紹介してもらったサイト張っておきます(アイデアの参考になるかもしれないと思って)。
→https://lgtmoon.herokuapp.com/
案の一つとして有名なザッカーバーグの言葉をちょっともじってやってみるのも面白いかもしれないと思いました。
→https://image.lgtmoon.dev/117072

**Comment by takeshi8989** [comment]
これ実際に遊んでみたんですけど、160回目くらいでこのURがでたときめちゃくちゃうれしかったし爆笑しました（笑）
