### ISSUE TITLE
Recursionユーザーの情報集めと許可取り

### ISSUE THREAD

**Issue by takeshi8989** [recursion-teamdev-green/project#2]
写真とその他の情報などをお願いします！

**Comment by jKai-Hw** [comment]
- [ ] ガチャ結果画面に出す情報の決定
- [ ] ガチャに入れるRecursionメンバーのリストアップ(今のところ、共同創業者枠、メンター枠、よくDiscodeで質問に回答してる枠、はずれレアリティ枠としてチームGreenメンバー3人)
- [ ] リストアップしたメンバーへ連絡し、許可取りと情報提供してもらう
- [ ] さらにリストに入れる人を増やすか検討(Recursion中心メンバー→ワークショップ計画者、最古参勢、公式イベント講師など)

**Comment by takeshi8989** [comment]
個人的には２と３は同じランクでいいのかなとも思うのですがいかがでしょうか？
あまり優劣をつけすぎると失礼になると思うので。
リストは多ければ多いほど面白いと思います！

**Comment by jKai-Hw** [comment]
2と3が同じランクというのは、自分もそう思ってました！
N→Greenメンバー
R→メンターさんなど
SR→共同創業者
UR→(かなり低確率)実際のShinyaさんの顔写真入りや魔改造Jeffyさんなどネタ枠で作っても面白いかもしれない
みたいな感じで想像してたのですがどうでしょうか？URは入れるかやその内容は、皆さんの判断も聞きたいです！

リストは初心者さんに知ってもらいたいという目的があるので、あまり多すぎるとこんがらがって利用しにくいかなと思って、最初は少なめにしてました。
増やすのも面白いと思います！ただ、その場合にはガチャの一覧ページみたいなもの
例
‐　SR(確率5％)
　‐共同創業者
　　‐Shinyaさん
　　‐Jeffyさん
‐　R(確率20％)
　‐メンター
　　‐Reinaさん
　‐よく質問に答えてくれる人
　　‐～さん
みたいなページを作ったほうがいいと思います。(できれば出た人の文字を濃くするなどのギミックが欲しい)
人数を増やすのはこの機能を作れることが確定してからのがいいかなと思いました。

**Comment by jKai-Hw** [comment]
一応今リストアップしているメンバーさんです

- Shinyaさん
- Jeffyさん

- レイナさん　最古参　コミュニティマネージャー　初心者用チーム開発メンター
- Achaさん　初心者用チーム開発メンター
- Kwonさん　初心者用チーム開発メンター
- ハルキさん　初心者用チーム開発メンター

↑以上が確定で入れたほうがいいと思っている人たち　質問によく答えてくれる人はShinyaさんに聞いてみようと思っています。

- ・その他の候補者

- Noriさん　Shinyaさんが尊敬してる人　最古参　OSS開発した人→木構造グラフィックを開発した人
- Sorasukeさん　最近よくイベントを計画してくれてる
- あちょさん
- Ryuさん　Recursionの公式イベントの講師
- Hiroさん　もくもく会のホスト　最近休んでるかも
- Keisuke　最古参
- Takaさん　初心者交流ワークショップ計画者
- mcnLeandroさん　チーム開発のメンターさん
- Masaさん メンター枠 https://twitter.com/soylove2

**Comment by takeshi8989** [comment]
魔改造Jeffryさんで爆笑しましたwww
めちゃくちゃいいアイデアだと思うので採用しましょう！w
一覧見ましたがいい感じですね！とりあえず候補者全員にお願いして聞いてみてください！

自分のイメージでは、UR2(約0.5%), SR2(約3%), R10(約20%), N 20-30(約75％)の感じです。
ただ、基本的にはKaiさんが全部決めちゃっていいですよ！

トップページにはランダムで10人くらいを表示するつもりで画像をのせてみました。ランダムなので毎回変わります
一覧があって獲得後に文字が太くなる機能いいですね！Issueに追加しておきます！
