### ISSUE TITLE
twitter widgetの有効化

### ISSUE THREAD

**Issue by purin213** [recursion-teamdev-green/project#28]
現在JSで生成したresultPageに対してTwitterのウィジェットが動いていない状態です。この状況だと

1. ツイートボタンが表示されなく、ただのリンクになる
2. 事前にツイート内容が埋め込まれる機能が動かなくなる

の様な動作になってしまいます、自分の力では少し理解できない部分もあるのでヘルプいただきたいです。

DOCS：[http://westplain.sakuraweb.com/translate/twitter/Documentation/Twitter-for-Websites/JavaScript/Scripting-Loading-and-Initialization.cgi](url)

**Comment by jKai-Hw** [comment]
このIssuesは最初にTaroさんが作ってくれたTwitterへ結果を投稿する機能が、今は正しく表示されていないってことであってますか？
だとしたらたぶん、HTMLファイルの一番下のスクリプトタグがなくなっているか、もしくはJSファイルの一番下のTwitter関係のっぽいコードが一行コメントアウトされてるのは関係ないでしょうか？

**Comment by takeshi8989** [comment]
やってみます

**Comment by purin213** [comment]
有難うございます😭
