### ISSUE TITLE
Twitterに投稿する機能の調査

### ISSUE THREAD

**Issue by takeshi8989** [recursion-teamdev-green/project#3]
SR(Shinyaさん)などが出たときにTwitterに投稿できる機能。
どんな情報が欲しいか(Twitterのユーザーアカウントやガチャ結果など)の報告をよろしくお願いします！

**Comment by takeshi8989** [comment]
やはりSRに限らずいつでもTwitterに投稿できるようにしたほうが良いと思いました。
例えばレイナさんがレイナさんを当てたときにTweetしたりできるからです

**Comment by purin213** [comment]
プルリク#10にて機能追加しました。
[https://github.com/recursion-teamdev-green/project/pull/10](url)
